services:
  cleanup:
    container_name: cleanup
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=${PORT}
      - INTERVAL_MINUTE=${INTERVAL_MINUTE}
      - CRON_HOUR=${CRON_HOUR}
      - DURATION_DAYS=${DURATION_DAYS}
    ports:
      - "8887:8888"
    volumes:
      - ${ROOT_MEDIA_PATH}:/media
      - ${MOVIES_PATH}:/media/tvshows
      - ${TV_SHOWS_PATH}:/media/movies



