services:
  cleanup:
    container_name: cleanup
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8888
      - INTERVAL_MINUTE=1
      - CRON_HOUR=10
    ports:
      - "8888:8888"
    volumes:
      - ./media:/media
      - ./media/tvshows:/media/tvshows
      - ./media/movies:/media/movies



